:source-highlighter: highlightjs
:title: Navigating the Admin
:sectlinks: true
:icons: font
:module: BroadleafCommercePrivate
:module-images: images/{module}/
:chapter: Basics
:chapter-section: Navigation
:guide-type: admin
:url-key: admin-navigation
:document-url: /{guide-type}/{chapter}/{chapter-section}/{url-key}

[subs="attributes"]
= {title}

This guide will teach you the basics of navigating the default Broadleaf Admin application.

== Admin Modules and Sections

[instruction]
--
The left navigation bar is where all admin navigation modules live. It is the base for navigation to
all sections and pages of admin. The different sections and pages of the Admin are generally grouped together by concept
to the corresponding admin module.
--

[instruction]
--
Here is a sample list of Broadleaf admin modules and some of their corresponding sections.
++++
<u><b>Broadleaf Admin Modules and Sections</u></b>
++++


[horizontal]
Catalog:::
Catalogs, Category, Product, Inventory, Product Options, etc.

Content:::
Menus, Content Items, URL Redirects, Media Assets, etc.

Customer Care:::
Accounts, Customers, CSR Orders, Customer Segments, Return Authorizations, Gift Card Accounts, etc.

Design:::
Theme Configurations, Widgets, Content Zones, etc.

Internationalization:::
 Regional Forms, Messages, etc.

Pricing:::
Offers, Price List, Contracts, Sales, etc.

Search:::
Redirects, Relevancy Rules, Type Ahead Configuration, Search Facets, etc.

Settings:::
Sandboxes, Custom Fields, Admin Users, System Properties, Page Types, etc.

Site Updates:::
Current User Changes, Approvals, Workflow Audit, Deployments, Change History, etc.

Sites:::
Standard Sites, Template Sites, etc.
--
